language: cpp
dist: trusty

compiler:
  - clang
  - gcc

env:
  global:
    - CXXFLAGS="-O0 -g"

addons:
  apt:
    packages:
      - libgtest-dev

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux:
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after_success.sh
