language: cpp
dist: trusty
sudo: true

env:
  global:
    - CXXFLAGS="-O0 -g"

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - compiler: clang
      env:
        - MATRIX_EVAL=""

before_install:
  - ./.travis/before_install.sh
  - eval "${MATRIX_EVAL}"

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after_success.sh
