language: cpp
dist: trusty
sudo: true

env:
  global:
    - CXXFLAGS="-O0 -g"

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - echo deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main | sudo tee /etc/apt/sources.list.d/llvm-toolchain.list
  - sudo apt-get update -qq
  - sudo apt-get install libpcre2-dev libgtest-dev g++-6 clang-4.0
  - eval "${MATRIX_EVAL}"

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after_success.sh
